### ISSUE TITLE
HA not loading currentcost module

### ISSUE THREAD

**Issue by marc252** [lolouk44/CurrentCost_HA_CC#21]
---
name: Bug report
about: Create a report to help us improve
title: ''home assistant 2023.6.0 refuses to load currentcost component
labels: bug
assignees: ''

---

**Describe the bug**
After updating home assistant, currentcost module doesn't work any more

**To Reproduce**
Install currentcost under home assistant 2023.6.0, after adding platfform currentcost to configuration.yaml check configuration and the error will be generated

**Desktop/Server/Device (please complete the following information):**
 - Device used to run the Custom Component Raspberry pi
 - Method of installation HACS
 - Version of the Custom Component installed? 0.2.4

**Logs**
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/currentcost/sensor.py:7
Integration: currentcost (documentation, issues)
First occurred: 21:47:16 (1 occurrences)
Last logged: 21:47:16

Unexpected exception importing platform custom_components.currentcost.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/currentcost/sensor.py", line 7, in <module>
    import serial_asyncio
  File "/usr/local/lib/python3.11/site-packages/serial_asyncio/__init__.py", line 408, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

```

**Comment by marc252** [comment]
Looks like modifying requirements in custom_components/currentcost/manifest.json from:
"pyserial-asyncio==0.4",
to 
"pyserial-asyncio==0.6",

Solves the issue

**Comment by nacbooth** [comment]
Same problem: the stated solution seems to have got things back in order (after a couple of restarts, as usual!).  

Thanks for the tip.

**Comment by DanielDomB** [comment]
> 

Yes thanks for the tip, that solved it

**Comment by masxmedia** [comment]
Was also having same problem and changing 'pyserial-asyncio==0.6' fixed it. Thank you!

**Comment by Coooogz** [comment]
This fix worked for me too thanks. Seems I needed a reboot after change was made.

**Comment by PatrikNorrgard** [comment]
I tried the fix aswell, but HA won´t let me restart:
[140359694122896] The system cannot restart because the configuration is not valid: Platform error sensor.currentcost - Exception importing custom_components.currentcost.sensor

How did you manage to restart?

Edit: Forcing a restart from Proxmox did the job.

**Comment by vw-kombi** [comment]
Thanks heaps for this - I have no idea how you find out these answers but I am on the latest and working again.

**Comment by ThePPL** [comment]
Thanks @marc252. Your fix works great. I'm not sure why the commits by @HarvsG have not been merged and released.  This caused me hours of headaches today trying to get this to work before I came across your post!

Maybe this project has been abandoned?

**Comment by BertQuodge** [comment]
Thanks for the tip, worked for me too.

**Comment by NotASecretAgent** [comment]
Thank you for posting this fix
