### ISSUE TITLE
Error while setting up currentcost platform for sensor / Error while adding currentcost platform entities HA 2023.9

### ISSUE THREAD

**Issue by Majestic7979** [lolouk44/CurrentCost_HA_CC#23]
```
2023-09-24 09:56:15.339 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.currentcost
2023-09-24 09:56:15.463 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform currentcost
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
entity.add_to_platform_start(
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 211, in add_to_platform_start
self._async_read_entity_options()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 785, in _async_read_entity_options
registry.async_update_entity_options(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1025, in async_update_entity_options
old = self.entities[entity_id]
~~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/local/lib/python3.11/collections/__init__.py", line 1126, in __getitem__
raise KeyError(key)
KeyError: None
2023-09-24 09:56:15.494 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up currentcost platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
entity.add_to_platform_start(
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 211, in add_to_platform_start
self._async_read_entity_options()
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 785, in _async_read_entity_options
registry.async_update_entity_options(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1025, in async_update_entity_options
old = self.entities[entity_id]
~~~~~~~~~~~~~^^^^^^^^^^^
File "/usr/local/lib/python3.11/collections/__init__.py", line 1126, in __getitem__
raise KeyError(key)
KeyError: None
```

**Comment by john-coleman** [comment]
@Majestic7979  See also https://github.com/lolouk44/CurrentCost_HA_CC/pull/22
